### PR TITLE
fix: Update invoice link method for compatibility with packing slips

### LINKED ISSUE #30: ❗ PHP Fatal Error: Undefined Method `my_account_invoice_pdf_link()` in Dokan Invoice Module
## **Description**
While validating the Dokan Invoice module under standard plugin conditions, a critical PHP fatal error is triggered when accessing invoice-related functionality. The error indicates that the system attempts to call a method — `my_account_invoice_pdf_link()` — that does not exist within the `WPO\IPS\Frontend` class.  

This issue creates a full application halt, impacting both frontend and backend flows that rely on invoice PDF generation, and blocks normal vendor/store operations tied to invoice accessibility. From a QA lens, this represents a hard failure that needs investigation into class loading, method availability, and cross-module compatibility (Dokan Invoice ↔ Germanized/WCPDF).

## **Actual Behavior**
A fatal error is thrown immediately:

PHP Fatal error:  Uncaught Error: Call to undefined method
WPO\IPS\Frontend::my_account_invoice_pdf_link()
in wp-content/plugins/dokan-invoice/dokan-invoice.php:220

- Execution stops entirely.
- The invoice PDF link cannot be generated or displayed.
- The system attempts to call a method that is missing or deprecated.
- Impacts any workflow that calls the related invoice PDF action.

## **Expected Behavior**
- The method responsible for generating or displaying invoice PDF links should exist and execute without fatal errors.
- The invoicing workflow should load properly with no interruption.
- Users should be able to access invoice PDFs from the expected interface without system crashes.

## **Screenshot or Video**
_Add a screenshot or screen recording showing the fatal error or the action triggering it._

## **Additional Info**
- **File causing issue:** `wp-content/plugins/dokan-invoice/dokan-invoice.php` on line 220  
- **Error Source Class:** `WPO\IPS\Frontend`  
- **Error Type:** Fatal — undefined method  
- **Environment:**  
  - WordPress environment using Dokan + Dokan Invoice  
  - PHP version not specified, but likely 8.x based on default test setups  
- **Steps to Reproduce:**  
  1. Enable Dokan and Dokan Invoice modules.  
  2. Access any page where invoice PDF links should render (e.g., vendor dashboard, order details, My Account > Orders).  
  3. Observe fatal error in logs and frontend crash.

@jamil-mahmud @shohag121 @mrabbani  need to resolve as soon as possible since that breaks order page

### PR DESCRIPTION
**Pull request by kzamanbd**
## Closes

* Closes https://github.com/getdokan/dokan-invoice/issues/30

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved invoice listing action handling to work consistently across frontend API versions.
  * Added fallback behavior so invoice actions continue to display when newer or legacy frontend implementations are missing.
  * Ensured backward compatibility so existing setups remain unaffected while supporting newer frontend integrations.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: dokan-invoice.php [hunk 1]
```diff
@@ -222,7 +222,21 @@ public function dokan_invoice_listing_actions_my_account( $actions, $order ) {
 
 	    $frontend = new \WPO\IPS\Frontend();
 
-	    return $frontend->my_account_invoice_pdf_link( $actions, $order );
+        /**
+         * Remove there method my_account_invoice_pdf_link and replace with my_account_invoice_actions;
+         * 
+         * @see https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/1149/files#diff-013084d12b13282bd1e87d50f2529347934e978c722e5bbf332b1bfc4dcbdd47L38
+         */
+
```
Comment (MdAsifHossainNadim) [inline dokan-invoice.php:231]: Remove the extra lines from here

**Review by MdAsifHossainNadim — APPROVED** [review]

File: dokan-invoice.php (hunk 1 above)
Comment (kzamanbd) [reply dokan-invoice.php:231]: Removed

**Review by shohag121 — APPROVED** [review]
LTGM
